name: Matrix Example

permissions:
   contents: read

on:
  workflow_dispatch:
  push:

jobs:
  get-image:
    name: Get image to build
    runs-on: ubuntu-24.04
    outputs:
      images: ${{ steps.changed-folders.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Get changed image folders
        id: changed-folders
        uses: tj-actions/changed-files@v47
        with:
          diff_relative: 'true'
          dir_names: 'true'
          dir_names_exclude_current_dir: 'true'
          dir_names_max_depth: '2'
          path: 'images/'
          matrix: true
      - name: List all changed image folders
        run: echo '${{ steps.changed-folders.outputs.all_changed_files }}'

  build-image:
    name: Build Image
    if: (needs.get-image.outputs.images != '[]')
    runs-on: ubuntu-24.04
    needs: [get-image]
    strategy:
      matrix: 
        images: ${{ fromJSON(needs.get-image.outputs.images) }}
        architecture: [linux-arm64, linux-amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        run: |
          echo ${{ matrix.images }}/${{ matrix.architecture }}
