name: Matrix Example

permissions:
   contents: read

on:
  workflow_dispatch:
  push:

jobs:
  get-tags:
    name: Get changed tag folders
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-folders.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Get changed folders
        id: changed-folders
        uses: tj-actions/changed-files@v47
        with:
          diff_relative: 'true'
          dir_names: 'true'
          dir_names_exclude_current_dir: 'true'
          dir_names_max_depth: '1'
          matrix: true
      - name: List all changed folders
        run: echo '${{ steps.changed-folders.outputs.all_changed_files }}'

  matrix-job:
    name: Run Matrix Job
    if: (needs.get-tags.outputs.matrix != '')
    runs-on: ubuntu-latest
    needs: [get-tags]
    strategy:
      matrix: 
        folders: ${{ fromJSON(needs.get-tags.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        run: |
          echo ${{ matrix.folders }}
